#!/usr/bin/env sh

# This file was generated by the Gradle 'wrapper' task.
# Do not edit this file directly.
# Use the 'gradle wrapper' task to regenerate this file.

# Resolve the directory for this script
PRG="$0"

while [ -h "$PRG" ]; do
  LS="$(ls -ld "$PRG")"
  LINK="$(expr "$LS" : '.*-> \(.*\)$')"
  if expr "$LINK" : '/.*' > /dev/null; then
    PRG="$LINK"
  else
    PRG="$(dirname "$PRG")/$LINK"
  fi
done

APP_HOME="$(dirname "$PRG")"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/bin/java" ] ; then
        JAVA_EXE="$JAVA_HOME/jre/bin/java"
    else
        JAVA_EXE="$JAVA_HOME/bin/java"
    fi
else
    JAVA_EXE="java"
fi

# Set the classpath to the wrapper jar
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Execute the wrapper
exec "$JAVA_EXE" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
